<template>
  <div class="text-center">
    <div class="loadingio-spinner-spinner-l8domjhu7">
      <div class="ldio-on328hzqv">
        <div /><div /><div /><div /><div /><div /><div /><div /><div />
      </div>
    </div>
  </div>
</template>
<style type="text/css">
@keyframes ldio-on328hzqv {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-on328hzqv div {
  left: 47px;
  top: 24px;
  position: absolute;
  animation: ldio-on328hzqv linear 1.2048192771084336s infinite;
  background: #000000;
  width: 6px;
  height: 12px;
  border-radius: 1.92px / 1.92px;
  transform-origin: 3px 26px;
}.ldio-on328hzqv div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -1.07095046854083s;
  background: #000000;
}.ldio-on328hzqv div:nth-child(2) {
  transform: rotate(40deg);
  animation-delay: -0.9370816599732261s;
  background: #000000;
}.ldio-on328hzqv div:nth-child(3) {
  transform: rotate(80deg);
  animation-delay: -0.8032128514056224s;
  background: #000000;
}.ldio-on328hzqv div:nth-child(4) {
  transform: rotate(120deg);
  animation-delay: -0.6693440428380187s;
  background: #000000;
}.ldio-on328hzqv div:nth-child(5) {
  transform: rotate(160deg);
  animation-delay: -0.535475234270415s;
  background: #000000;
}.ldio-on328hzqv div:nth-child(6) {
  transform: rotate(200deg);
  animation-delay: -0.4016064257028112s;
  background: #000000;
}.ldio-on328hzqv div:nth-child(7) {
  transform: rotate(240deg);
  animation-delay: -0.2677376171352075s;
  background: #000000;
}.ldio-on328hzqv div:nth-child(8) {
  transform: rotate(280deg);
  animation-delay: -0.13386880856760375s;
  background: #000000;
}.ldio-on328hzqv div:nth-child(9) {
  transform: rotate(320deg);
  animation-delay: 0s;
  background: #000000;
}
.loadingio-spinner-spinner-l8domjhu7 {
  width: 91px;
  height: 91px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-on328hzqv {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.91);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-on328hzqv div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
